[versions]

## project
# plugin
plugin-gradle-android = "9.3.1"
plugin-ben-manes = "0.61.0"
plugin-licensee = "1.14.1"
plugin-google-services = "4.5.0"
plugin-firebase-crashlytics = "3.0.7"
plugin-firebase-perf = "2.0.2"
plugin-ksp = "2.3.11"

## common
# buildType
build-type-debug = "debug"
build-type-release = "release"
# build
version-name = "1.0.4"
build-tools-version = "37.0.0"
sdk-min = "26"
sdk-compile = "37"
sdk-compile-extension = "15" # for compileSdk 35
sdk-target = "36"
jvm-target = "17"
jvm-target-kotlin = "17"

# kotlin
kotlin = "2.4.10"
kotlin-atomic = "0.33.0"
kotlin-coroutines = "1.11.0"
kotlin-immutable-collections = "0.5.1"
kotlin-serialization-json = "1.11.0"
kotlin-time = "0.8.0"

# ui
# jetpack
jetpack-core = "1.19.0"
jetpack-activity = "1.13.0"
jetpack-annotation = "1.10.0"
jetpack-appcompat = "1.7.1"
jetpack-browser = "1.10.0"
jetpack-lifecycle = "2.11.0"
jetpack-splash = "1.2.0"
# compose
compose-bom = "2026.06.01"
compose-activity = "1.13.0"
compose-constraintlayout = "1.1.2"
# navigation
compose-navigation = "1.1.5"

## frameworks
# firebase
firebase-bom = "34.17.0"
# ad
ads = "25.0.0"
# database
room = "2.8.4"
# di
di-hilt = "2.60.1"
di-hilt-navigation-compose = "1.4.0"
# io
data-store = "1.2.1"
# utils
jdk-desugar = "2.1.5"
leakcanary = "2.14"
timber = "5.0.1"
# test
junit4 = "4.13.2"
mockk = "1.14.11"
# androidTest
androidx-test = "1.7.0"
androidx-test-ext-junit = "1.3.0"

[libraries]

# kotlin
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-atomic = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlin-atomic" }
kotlin-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlin-coroutines" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
kotlin-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services" }
kotlin-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable-collections" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }
kotlin-time = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-time" }

## ui
# jetpack
jetpack-core = { module = "androidx.core:core-ktx", version.ref = "jetpack-core" }
jetpack-activity = { module = "androidx.activity:activity", version.ref = "jetpack-activity" }
jetpack-annotation = { module = "androidx.annotation:annotation", version.ref = "jetpack-annotation" }
jetpack-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "jetpack-appcompat" }
jetpack-browser = { module = "androidx.browser:browser", version.ref = "jetpack-browser" }
jetpack-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "jetpack-lifecycle" }
jetpack-splash = { module = "androidx.core:core-splashscreen", version.ref = "jetpack-splash" }
jetpack-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetpack-lifecycle" }
jetpack-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "jetpack-lifecycle" }
# compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintlayout" }
# navigation
compose-navigation-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "compose-navigation" }
compose-navigation-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "compose-navigation" }

## frameworks
# firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
# ad
ads = { module = "com.google.android.gms:play-services-ads-lite", version.ref = "ads" }
# database
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
# di
di-hilt = { module = "com.google.dagger:hilt-android", version.ref = "di-hilt" }
di-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "di-hilt-navigation-compose" }
di-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "di-hilt" }
# io
data-store = { module = "androidx.datastore:datastore-preferences", version.ref = "data-store" }
# util
jdk-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "jdk-desugar" }
leakcanary = { module = "com.squareup.leakcanary:plumber-android", version.ref = "leakcanary" }
leakcanary-debug = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
# test
junit4 = { module = "junit:junit", version.ref = "junit4" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
# androidTest
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "di-hilt" }

[plugins]

# common
ben-manes = { id = "com.github.ben-manes.versions", version.ref = "plugin-ben-manes" }
licensee = { id = "app.cash.licensee", version.ref = "plugin-licensee" }

# kotlin
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-ksp" }

# modules
android-application = { id = "com.android.application", version.ref = "plugin-gradle-android" }
android-library = { id = "com.android.library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# ui
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# di
di-hilt = { id = "com.google.dagger.hilt.android", version.ref = "di-hilt" }

# google / firebase
google-services = { id = "com.google.gms.google-services", version.ref = "plugin-google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "plugin-firebase-crashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "plugin-firebase-perf" }

# database
room = { id = "androidx.room", version.ref = "room" }

[bundles]

# kotlin
kotlin-bom = ["kotlin-stdlib"]
kotlin-common = [
    "kotlin-atomic",
    "kotlin-immutable-collections",
    "kotlin-serialization-json",
    "kotlin-time",
]

# ui
common = [
    "jetpack-annotation",
    "jetpack-appcompat",
    "jetpack-core",
    "jetpack-common",
    "jetpack-viewmodel",
    "jetpack-viewmodel-savedstate",
]
ui = [
    "jetpack-activity",
    "jetpack-browser",
    "jetpack-splash",
]
navigation = [
    "compose-navigation-ui",
    "compose-navigation-runtime",
]

# compose
compose = [
    "compose-activity",
    "compose-constraintlayout",
    "compose-foundation",
    "compose-material3",
    "compose-ui",
    "compose-tooling-preview",
]
compose-tooling = [
    "compose-runtime-tracing",
    "compose-tooling",
]

# framework
firebase-bom = [
    "firebase-analytics",
    "firebase-crashlytics",
    "firebase-perf",
]
database = ["room-runtime"]
database-compiler = ["room-compiler"]
di = ["di-hilt", "di-hilt-navigation-compose"]
di-compiler = ["di-hilt-compiler"]
coroutines-bom = [
    "kotlin-coroutines",
    "kotlin-coroutines-android",
    "kotlin-coroutines-play-services",
]

# test
test = [
    "junit4",
    "mockk",
    "kotlin-coroutines-test",
]
# androidTest
android-test = [
    "compose-test-junit4",
    "androidx-test-runner",
    "androidx-test-ext-junit",
    "hilt-android-testing",
]
